# Generated by Django 5.1.2 on 2024-11-06 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('public', models.BooleanField(default=False, help_text='Is it visible to all roles', verbose_name='Public')),
                ('draft', models.BooleanField(default=False, help_text='Is it still a draft', verbose_name='Draft')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
            ],
            options={
                'verbose_name': 'Material category',
                'verbose_name_plural': 'Material categories',
            },
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('name', models.CharField(max_length=255, verbose_name='Building name/code')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('zip', models.IntegerField(verbose_name='ZIP')),
                ('category', models.CharField(choices=[('HO', 'Homes'), ('AP', 'Apartments'), ('HL', 'Hotels'), ('RE', 'Resorts'), ('RT', 'Retail'), ('IN', 'Instustrial'), ('OF', 'Office'), ('HE', 'Healthcare'), ('ED', 'Education'), ('MI', 'Mixed Use'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Building category')),
                ('subcategory', models.CharField(choices=[('HO', 'Homes'), ('AP', 'Apartments'), ('HL', 'Hotels'), ('RE', 'Resorts'), ('RT', 'Retail'), ('IN', 'Instustrial'), ('OF', 'Office'), ('HE', 'Healthcare'), ('ED', 'Education'), ('MI', 'Mixed Use'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Building subcategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
            options={
                'verbose_name': 'Structural component',
                'verbose_name_plural': 'Structural components',
            },
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Material category',
                'verbose_name_plural': 'Material categories',
            },
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='StructuralComponent',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('name', models.CharField(max_length=255, verbose_name='Structural component name')),
                ('surface', models.DecimalField(decimal_places=3, help_text='Unit is m²', max_digits=10, verbose_name='Surface')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
            options={
                'verbose_name': 'Structural component',
                'verbose_name_plural': 'Structural components',
            },
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('name', models.CharField(max_length=255, verbose_name='Marerial name')),
                ('density', models.DecimalField(decimal_places=3, help_text='Unit is Kg/m³', max_digits=10, verbose_name='Density')),
                ('emissions', models.DecimalField(decimal_places=3, help_text='Unit is co²/kg', max_digits=10, verbose_name='Emissions')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.materialcategory')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
            bases=('pages.basemodel',),
        ),
        migrations.CreateModel(
            name='StructuralComponentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=3, help_text='Unit is m³', max_digits=10, verbose_name='Volume')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Unit is kg', max_digits=10, verbose_name='Weight')),
                ('area', models.DecimalField(decimal_places=3, help_text='Unit is m²', max_digits=10, verbose_name='Area')),
                ('thickness', models.DecimalField(decimal_places=3, help_text='Unit is m', max_digits=10, verbose_name='Thickness')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.material')),
                ('structural_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.structuralcomponent')),
            ],
            options={
                'verbose_name': 'Structural component material',
                'verbose_name_plural': 'Structural component materials',
            },
        ),
        migrations.AddField(
            model_name='structuralcomponent',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='structural_components', through='pages.StructuralComponentMaterial', to='pages.material'),
        ),
        migrations.CreateModel(
            name='BuildingStructuralComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='How many of components', max_digits=10, verbose_name='Quantity')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.building')),
                ('structural_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.structuralcomponent')),
            ],
            options={
                'verbose_name': 'Building structural component',
                'verbose_name_plural': 'Building structural components',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='structural_components',
            field=models.ManyToManyField(blank=True, related_name='buildings', through='pages.BuildingStructuralComponent', to='pages.structuralcomponent'),
        ),
    ]
