# Generated by Django 5.1.2 on 2024-11-06 16:11

from django.db import migrations

CATEGORIES_DICT = {
    "Homes": [
        "Low income",
        "Middle income",
        "High income",
    ],
    "Apartments": ["Low income", "Middle income", "High income", "Serviced apartment"],
    "Hotels": [
        "1 star",
        "2 star",
        "3 star",
        "4 star",
        "5 star",
    ],
    "Resorts": [
        "1 star",
        "2 star",
        "3 star",
        "4 star",
        "5 star",
    ],
    "Retail": [
        "Department Store",
        "Shopping Mall",
        "Supermarket",
        "Small Food Retail",
        "Non-food Big Box Retail",
    ],
    "Instustrial": [
        "Light Industry",
        "Warehouse",
    ],
    "Office": ["Grade A" "Grade B" "Grade C"],
    "Healthcare": [
        "Nursing Homes",
        "Private Hospital",
        "Public Hospital",
        "Multi-specialty Hospital",
        "Clinics",
        "Diagnostic Center",
        "Teaching Hospital",
        "Eye Hospital",
        "Dental Hospital",
    ],
    "Education": [
        "Preschool",
        "School",
        "University",
        "Sports Facilities",
        "Other Educational Facilities",
    ],
    "Mixed Use": ["Self-defined building"],
}


def create_default_categories(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    BuildingCategory = apps.get_model("pages", "BuildingCategory")
    BuildingSubcategory = apps.get_model("pages", "BuildingSubcategory")
    for category, subcategories in CATEGORIES_DICT.items():
        # There is a function get_or_create() that avoids this repeated code but comes with some issues
        category_obj, _ = BuildingCategory.objects.get_or_create(name=category)
        for subcategory in subcategories:
            subcategory_obj, _ = BuildingSubcategory.objects.get_or_create(
                name=subcategory
            )
            subcategory_obj.categories.add(category_obj)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
