# Generated by Django 5.1.2 on 2024-12-05 15:44

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'material_category_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_load_building_categories'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
