# Generated by Django 5.1.2 on 2024-12-27 16:46

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'assembly_category_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_load_material_categories'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
