# Generated by Django 5.1.2 on 2024-12-27 16:46

import json
import os

from django.db import connection, migrations


def load_fixture(apps, schema_editor):
    """Load the assembly category/technique seed data.

    Loads via the HISTORICAL models (apps.get_model) and only writes the fields
    that exist at this point in the migration graph. This avoids depending on
    columns added by later migrations (e.g. AssemblyCategory.family in 0047),
    which would break a fresh `migrate` if we used `loaddata` (that uses the
    current model). Produces the same end state as the original loaddata.
    """
    AssemblyCategory = apps.get_model("pages", "AssemblyCategory")
    AssemblyTechnique = apps.get_model("pages", "AssemblyTechnique")
    ACT = apps.get_model("pages", "AssemblyCategoryTechnique")

    fixture_path = os.path.join(
        os.path.dirname(__file__), "..", "fixtures", "assembly_category_data.json"
    )
    with open(fixture_path, encoding="utf-8") as fh:
        records = json.load(fh)

    for rec in records:
        model = rec["model"]
        pk = rec["pk"]
        f = rec["fields"]
        if model == "pages.assemblycategory":
            AssemblyCategory.objects.update_or_create(
                pk=pk, defaults={"name": f["name"], "tag": f.get("tag", "")}
            )
        elif model == "pages.assemblytechnique":
            AssemblyTechnique.objects.update_or_create(
                pk=pk, defaults={"name": f["name"]}
            )
        elif model == "pages.assemblycategorytechnique":
            ACT.objects.update_or_create(
                pk=pk,
                defaults={
                    "category_id": f["category"],
                    "technique_id": f["technique"],
                    "description": f.get("description"),
                },
            )

    # We inserted rows with explicit PKs, which does NOT advance the Postgres
    # id sequences (loaddata would normally do this for us). Reset them so later
    # auto-PK inserts (e.g. new categories created in migration 0046) don't
    # collide with these fixture PKs.
    with connection.cursor() as cursor:
        for model in (AssemblyCategory, AssemblyTechnique, ACT):
            table = model._meta.db_table
            cursor.execute(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                f"COALESCE((SELECT MAX(id) FROM {table}), 1))"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_load_material_categories'),
    ]

    operations = [
        migrations.RunPython(load_fixture, migrations.RunPython.noop)
    ]
