# Generated by Django 5.1.2 on 2025-01-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_load_assembly_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='impacts',
        ),
        migrations.DeleteModel(
            name='AssemblyImpact',
        ),
    ]
