# Generated by Django 5.1.2 on 2025-02-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customcity_customregion_alter_userprofile_city'),
        ('pages', '0004_load_assembly_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='reference_period',
            field=models.IntegerField(default=50, help_text='Number of years of building usage', verbose_name='Ref. period'),
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customregion'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customcity'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customcity'),
        ),
        migrations.AlterField(
            model_name='building',
            name='cond_floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross floor area [m^2]', max_digits=10, null=True, verbose_name='Conditioned Floor Area'),
        ),
        migrations.AlterField(
            model_name='epd',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customcity'),
        ),
    ]
