# Generated by Django 5.1.2 on 2025-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_load_assembly_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='climate_zone',
            field=models.CharField(choices=[('hot-dry', 'hot-dry'), ('warm-humid', 'warm-humid'), ('composite', 'composite'), ('temperate', 'temperate'), ('cold', 'cold'), ('tropical-wet', 'tropical wet')], max_length=50, verbose_name='Climate'),
        ),
        migrations.AlterField(
            model_name='building',
            name='cond_floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross floor area [m²]', max_digits=10, null=True, verbose_name='Conditioned Floor Area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='reference_period',
            field=models.IntegerField(default=50, help_text='Years of building use', verbose_name='Assessment time frame'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floor_area',
            field=models.DecimalField(decimal_places=2, help_text='Gross floor area [m²]', max_digits=10, verbose_name='Total Floor Area'),
        ),
    ]
