# Generated by Django 5.1.2 on 2025-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_building_reference_period_building_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='dimension',
            field=models.CharField(choices=[('area', 'm²'), ('length', 'm'), ('mass', 'kg'), ('volume', 'm³')], default='area', max_length=20, verbose_name='Assembly type'),
        ),
    ]
