# Generated by Django 5.1.2 on 2025-04-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_building_climate_zone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impact',
            unique_together={('impact_category', 'life_cycle_stage')},
        ),
        migrations.RemoveField(
            model_name='impact',
            name='unit',
        ),
    ]
