# Generated by Django 5.1.2 on 2025-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_impact_unique_together_remove_impact_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='cond_floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross floor area [m²]', max_digits=10, null=True, verbose_name='Conditioned floor area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floor_area',
            field=models.DecimalField(decimal_places=2, help_text='Gross floor area [m²]', max_digits=10, verbose_name='Total floor area'),
        ),
    ]
