# Generated by Django 5.1.2 on 2025-02-25 11:11

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "assembly_category_data_v2.json")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_assembly_dimension"),
    ]

    operations = [migrations.RunPython(load_fixture)]
