# Generated by Django 5.1.2 on 2025-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_load_assembly_category_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epd',
            name='type',
            field=models.CharField(choices=[('official', 'From a verified ILCD+EPD source'), ('custom', 'Created by user'), ('generic', 'Representative EPD for a country')], max_length=255, verbose_name='Type'),
        ),
    ]
