# Generated by Django 5.1.2 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_building_cond_floor_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='climate_zone',
            field=models.CharField(choices=[('hot-dry', 'Hot-dry'), ('warm-humid', 'Warm-humid'), ('composite', 'Composite'), ('temperate', 'Temperate'), ('cold', 'Cold'), ('tropical-wet', 'Tropical wet')], max_length=50, verbose_name='Climate'),
        ),
        migrations.AlterField(
            model_name='building',
            name='cooling_type',
            field=models.CharField(blank=True, choices=[('window-ac', 'Window air conditioners'), ('split-ac', 'Split air conditioners'), ('vrf-system', 'Variable refrigerant flow (VRF) systems'), ('packaged-ac', 'Packaged air conditioners'), ('chiller-system', 'Chiller systems'), ('other', 'Other cooling type')], max_length=50, null=True, verbose_name='Coolingting Type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('room-heater', 'Room heaters'), ('reverse_cycle_ac', 'Reverse cycle air conditioners (Heat pumps)'), ('split-ac', 'Split AC with heating mode'), ('packaged-ac', 'Packaged air conditioners with electric heating coils'), ('boiler', 'Boiler'), ('other', 'Other heating type')], max_length=50, null=True, verbose_name='Heating Type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lighting_type',
            field=models.CharField(blank=True, choices=[('led', 'LED (Light emitting diode) lights'), ('cfl', 'CFL (Compact fluorescent lamp) lights'), ('fluorescent-tube', 'T5 and T8 fluorescent tube lights'), ('other', 'Other lighting type')], max_length=50, null=True, verbose_name='Lighting Type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='ventilation_type',
            field=models.CharField(blank=True, choices=[('ahu', 'Air handling units (AHUs)'), ('fcu', 'Fan coil units (FCUs)'), ('cassette-ac', 'Ceiling or wall-mounted cassette ACs'), ('doas', 'DOAS'), ('other', 'Other ventilation type')], max_length=50, null=True, verbose_name='Ventilation Type'),
        ),
    ]
