# Generated by Django 5.1.2 on 2025-05-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_building_climate_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('scale_type', models.CharField(choices=[('nominal', 'Unordered categories (nominal)'), ('ordinal', 'Ordered categories (ordinal)'), ('cardinal', 'Numeric (interval/ratio)')], max_length=10, verbose_name='Scale Type')),
                ('scale_parameters', models.JSONField(blank=True, help_text='Scale-specific metadata', null=True, verbose_name='Scale Parameters')),
            ],
        ),
        migrations.CreateModel(
            name='EPDLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255, verbose_name='Score')),
                ('epd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.epd')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.label')),
            ],
            options={
                'unique_together': {('epd', 'label')},
            },
        ),
        migrations.AddField(
            model_name='epd',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='epd_labels', through='pages.EPDLabel', to='pages.label'),
        ),
    ]
