# Generated by Django 5.1.2 on 2025-02-25 11:11

from django.core.management import call_command
from django.db import migrations

from accounts.models import CustomUser


def load_fixture(apps, schema_editor):
    call_command("loaddata", "edge_epds_and_category.json")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_epd_type"),
    ]

    operations = [migrations.RunPython(load_fixture)]
