# Generated by Django 5.1.2 on 2025-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_building_climate_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epd',
            name='conversions',
            field=models.JSONField(blank=True, null=True, verbose_name='Conversions for units, follwoing EPDx'),
        ),
    ]
