# Generated by Django 5.1.2 on 2025-03-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_epd_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='classification',
        ),
        migrations.AddField(
            model_name='assembly',
            name='is_boq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.assemblycategorytechnique'),
        ),
    ]
