# Generated by Django 5.1.2 on 2025-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_load_edge_epds_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='is_boq',
            field=models.BooleanField(default=False),
        ),
    ]
