# Generated by Django 5.1.2 on 2025-05-28 11:31

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'epd_labels.json')

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_label_epdlabel_epd_labels'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]

