# Generated by Django 5.1.2 on 2025-03-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_building_cooling_capacity_building_cooling_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralproduct',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.assemblycategorytechnique'),
        ),
    ]
