# Generated by Django 5.1.2 on 2025-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_epd_conversions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epd',
            name='type',
            field=models.CharField(choices=[('official', 'From a verified ILCD+EPD source'), ('official_non_standard', 'Official from non ILCD + EPD format'), ('custom', 'Created by user'), ('generic', 'Representative EPD for a country')], max_length=255, verbose_name='Type'),
        ),
    ]
