# Generated by Django 5.1.2 on 2025-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_structuralproduct_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingassemblysimulated',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('tones', 'Tones'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('tones_km', 'Tones per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit of Quantity'),
        ),
        migrations.AlterField(
            model_name='epd',
            name='declared_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('tones', 'Tones'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('tones_km', 'Tones per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Declared Unit'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('tones', 'Tones'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('tones_km', 'Tones per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Impact Unit'),
        ),
        migrations.AlterField(
            model_name='operationalproduct',
            name='input_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('tones', 'Tones'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('tones_km', 'Tones per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit for quantity of EPD'),
        ),
        migrations.AlterField(
            model_name='simulatedoperationalproduct',
            name='input_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('tones', 'Tones'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('tones_km', 'Tones per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit for quantity of EPD'),
        ),
        migrations.AlterField(
            model_name='structuralproduct',
            name='input_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('tones', 'Tones'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('tones_km', 'Tones per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit for quantity of EPD'),
        ),
    ]
