# Generated by Django 5.1.2 on 2025-09-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_epd_conversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Mark this assembly as a template that can be reused in other buildings', verbose_name='Use as template'),
        ),
    ]
