# Generated by Django 5.1.2 on 2025-09-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0011_alter_epd_conversions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorysubcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorysubcategory',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Leave blank to mark this as universal', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
        migrations.AlterUniqueTogether(
            name='categorysubcategory',
            unique_together={('category', 'subcategory', 'country')},
        ),
    ]
