# Generated by Django 5.1.2 on 2025-04-09 15:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_buildingassemblysimulated_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epd',
            name='declared_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Reference Quantity of EPD'),
        ),
    ]
