# Generated by Django 5.1.2 on 2025-10-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_categorysubcategory_unique_together_and_more'),
        ('pages', '0012_alter_epd_type'),
    ]

    operations = [
    ]
