# Generated by Django 5.1.2 on 2025-04-09 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_buildingassemblysimulated_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='hours_per_week',
        ),
        migrations.AddField(
            model_name='building',
            name='hours_per_workday',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Operation hours per workday'),
        ),
        migrations.AlterField(
            model_name='operationalproduct',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_products', to='pages.building'),
        ),
        migrations.AlterField(
            model_name='simulatedoperationalproduct',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_operational_products', to='pages.building'),
        ),
    ]
