# Generated by Django 5.1.2 on 2026-01-08 09:21

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing buildings"""
    Building = apps.get_model('pages', 'Building')
    for building in Building.objects.all():
        building.uuid = uuid.uuid4()
        building.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_buildingoperation_coolingsystemairconditioner_and_more'),
    ]

    operations = [
        # Step 1: Add uuid field as nullable first
        migrations.AddField(
            model_name='building',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False, verbose_name='Building UUID'),
        ),
        # Step 2: Generate UUIDs for all existing buildings
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Make uuid non-nullable, unique, and add index
        migrations.AlterField(
            model_name='building',
            name='uuid',
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name='Building UUID'
            ),
        ),
    ]
