# Generated by Django 5.1.2 on 2025-09-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_assembly_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this template available to all users as a generic template', verbose_name='Public template'),
        ),
    ]
