# Generated by Django 5.1.2 on 2026-01-08 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_add_uuid_to_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotwatersystem',
            name='baseline_efficiency',
            field=models.DecimalField(db_column='baseline_efficiency_cop', decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baseline Hot Water System Efficiency (COP)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='energy_efficiency_label',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Energy Efficiency Star Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='equipment_efficiency_level',
            field=models.DecimalField(db_column='baseline_equipment_efficiency_percentage', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Baseline Hot Water System Equipment Efficiency Level (%)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='heat_recovery_system',
            field=models.BooleanField(db_column='heat_recovery_installed', default=False, verbose_name='Installation of Heat Recovery Systems'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='number_of_equipment',
            field=models.PositiveIntegerField(db_column='number_of_equipments', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Hot Water Equipment Installed'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='operating_days_per_week',
            field=models.PositiveSmallIntegerField(db_column='workdays_per_week', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Operating Days per Week'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='operating_hours_per_day',
            field=models.DecimalField(db_column='operation_hours_per_workday', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Operating Hours per Day'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='operating_weeks_per_year',
            field=models.PositiveSmallIntegerField(db_column='workweeks_per_year', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(52)], verbose_name='Operating Weeks per Year'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='power_input',
            field=models.DecimalField(db_column='power_input_kw', decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hot Water System Power Input (kW)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='type_of_hot_water_system',
            field=models.CharField(choices=[('heat-pump', 'Heat Pump Water Heater'), ('boiler', 'Boiler'), ('solar', 'Solar Water Heaters')], db_column='system_type', max_length=50, verbose_name='Type of Hot Water System'),
        ),
    ]
