# Generated by Django 5.1.2 on 2025-09-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_categorysubcategory_unique_together_and_more'),
        ('pages', '0012_alter_epd_type'),
        ('pages', '0013_add_is_public_to_assembly'),
    ]

    operations = [
    ]
