# Generated by Django 5.1.2 on 2026-02-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_hotwatersystem_number_of_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefrigerantGWP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrigerant_code', models.CharField(max_length=50, unique=True, verbose_name='Refrigerant Code')),
                ('gwp_value', models.PositiveIntegerField(verbose_name='GWP Value')),
            ],
            options={
                'verbose_name': 'Refrigerant GWP',
                'verbose_name_plural': 'Refrigerant GWP Values',
                'ordering': ['refrigerant_code'],
            },
        ),
    ]
