# Generated by Django 5.1.2 on 2025-09-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_merge_20250929_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='is_public',
        ),
    ]
