# Generated by Django 5.1.2 on 2025-09-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_assembly_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='from_template',
            field=models.ForeignKey(blank=True, help_text='The template this assembly was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_assemblies', to='pages.assembly'),
        ),
    ]
