# Generated by Django 5.1.2 on 2026-02-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_populate_refrigerant_gwp_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolingsystemairconditioner',
            name='packaged_subtype',
            field=models.CharField(blank=True, choices=[('rooftop', 'Rooftop Unit'), ('floor_standing', 'Floor-standing'), ('ductable', 'Ductable'), ('cassette', 'Cassette')], max_length=50, null=True, verbose_name='Packaged AC Sub-type'),
        ),
        migrations.AlterField(
            model_name='coolingsystemairconditioner',
            name='ac_type',
            field=models.CharField(choices=[('window', 'Window Air Conditioners'), ('split', 'Split Air Conditioners'), ('vrv', 'VRV/VRF (Variable Refrigerant Volume/Flow)'), ('packaged', 'Packaged/Ductable Air Conditioners')], max_length=50, verbose_name='Air Conditioners Type'),
        ),
        migrations.AlterField(
            model_name='coolingsystemchiller',
            name='baseline_cooling_efficiency_kw_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Baseline Cooling Efficiency (kW/RT)'),
        ),
    ]
