# Generated by Django 5.1.2 on 2026-02-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_cooling_system_types_and_decimal_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolingsystemairconditioner',
            name='number_of_stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Number of Stars (1–5)'),
        ),
        migrations.AddField(
            model_name='coolingsystemchiller',
            name='number_of_stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Number of Stars (1–5)'),
        ),
        migrations.AlterField(
            model_name='coolingsystemairconditioner',
            name='energy_efficiency_label',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True, verbose_name='Energy Efficiency Label (A–G)'),
        ),
        migrations.AlterField(
            model_name='coolingsystemchiller',
            name='energy_efficiency_label',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True, verbose_name='Energy Efficiency Label (A–G)'),
        ),
    ]
