# Generated by Django 5.1.2 on 2026-02-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_add_energy_label_and_stars_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventilationsystem',
            name='energy_efficiency_label',
        ),
        migrations.RemoveField(
            model_name='ventilationsystem',
            name='total_power_input_w',
        ),
        migrations.AddField(
            model_name='ventilationsystem',
            name='fresh_air_ratio_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fresh Air Ratio (%)'),
        ),
        migrations.AddField(
            model_name='ventilationsystem',
            name='number_of_stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Number of Stars (1–5)'),
        ),
        migrations.AddField(
            model_name='ventilationsystem',
            name='total_power_input_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Ventilation System Power Input (kW)'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='air_flow_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Air Flow Rate (CMH/CFM)'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='baseline_efficiency_w_cmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Baseline Ventilation System Efficiency (W/CMH)'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='ventilation_capacity',
            field=models.CharField(blank=True, choices=[('M3H', 'm³/hr'), ('F3M', 'ft³/min')], max_length=50, null=True, verbose_name='Ventilation Capacity'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='ventilation_type',
            field=models.CharField(choices=[('AHU', 'Air Handling Unit (AHU)'), ('FCU', 'Fan Coil Unit (FCU)'), ('CASSETTE_AC', 'Ceiling/Wall Mounted Cassette AC'), ('DOAS', 'Dedicated Outdoor Air System (DOAS)'), ('FAN', 'Ceiling/Exhaust/Wall Fan')], max_length=50, verbose_name='Ventilation Type'),
        ),
        # Make baseline_efficiency_w_cmh non-nullable (existing rows get 0)
        migrations.AlterField(
            model_name='ventilationsystem',
            name='baseline_efficiency_w_cmh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Baseline Ventilation System Efficiency (W/CMH)'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='baseline_efficiency_w_cmh',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Baseline Ventilation System Efficiency (W/CMH)'),
        ),
        # Make total_power_input_kw non-nullable (existing rows get 0)
        migrations.AlterField(
            model_name='ventilationsystem',
            name='total_power_input_kw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Ventilation System Power Input (kW)'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='total_power_input_kw',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Ventilation System Power Input (kW)'),
        ),
    ]