# Generated by Django 5.1.2 on 2026-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_ventilation_system_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingsystem',
            name='number_of_stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Number of Stars (1\u20135)'),
        ),
        migrations.AddField(
            model_name='lightingsystem',
            name='total_lighting_power_kw',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Lighting Power (kW)'),
        ),
        migrations.AddField(
            model_name='lightingsystem',
            name='tubes_per_fixture',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Tubes per Fixture'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='baseline_lighting_power_density',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Baseline Lighting Power Density (kW/m\xb2)'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='energy_efficiency_label',
            field=models.CharField(blank=True, choices=[('BEE', 'BEE Star Rating'), ('EGAT', 'EGAT Label No'), ('ESDM', 'ESDM decree'), ('OTHERS', 'Others')], max_length=10, null=True, verbose_name='Energy Efficiency Label'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='light_bulb_power_rating_w',
            field=models.PositiveIntegerField(verbose_name='Wattage per Fixture/Lamp (W)'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='lighting_bulb_type',
            field=models.CharField(choices=[('LED_PANEL', 'LED Panel'), ('LED_TUBE', 'LED Tube'), ('LED_DOWNLIGHT', 'LED Downlight'), ('LED_BULB', 'LED Bulb'), ('LED_STRIP', 'LED Strip'), ('FLUORESCENT_T5', 'Fluorescent T5'), ('FLUORESCENT_T8', 'Fluorescent T8'), ('FLUORESCENT_T12', 'Fluorescent T12'), ('CFL', 'CFL'), ('INCANDESCENT', 'Incandescent'), ('HALOGEN', 'Halogen'), ('METAL_HALIDE', 'Metal Halide'), ('HIGH_PRESSURE_SODIUM', 'High-Pressure Sodium')], max_length=50, verbose_name='Type of Lighting System'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='number_of_bulbs',
            field=models.PositiveIntegerField(verbose_name='Total Number of Fixtures Installed'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='room_type',
            field=models.CharField(choices=[('OFFICE_CONFERENCE', 'Office: Conference Room'), ('HOSPITAL_PATIENT', 'Hospital: Patient Room'), ('RESIDENTIAL_KITCHEN', 'Residential: Kitchen'), ('RESIDENTIAL_DINING', 'Residential: Dining Room'), ('COMMERCIAL_GENERAL', 'Commercial: General Office/Retail'), ('COMMERCIAL_MALL', 'Commercial: Mall / Department Store')], max_length=50, verbose_name='Room Type'),
        ),
    ]