# Generated by Django 5.1.2 on 2026-02-12 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_lighting_system_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotwatersystem',
            name='energy_efficiency_label',
        ),
        migrations.RemoveField(
            model_name='hotwatersystem',
            name='fuel_consumption',
        ),
        migrations.AddField(
            model_name='hotwatersystem',
            name='total_energy_consumption_kwh_per_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Energy Consumption Annually (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='baseline_efficiency',
            field=models.DecimalField(db_column='baseline_efficiency_cop', decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baseline Hot Water System Efficiency'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='fuel_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('light-fuel-oil', 'Light Fuel Oil'), ('heavy-fuel-oil', 'Heavy Fuel Oil'), ('lpg', 'LPG'), ('natural-gas', 'Natural Gas'), ('coal', 'Coal'), ('lignite', 'Lignite'), ('diesel', 'Diesel'), ('kerosene', 'Kerosene'), ('fire-wood-log', 'Fire Wood (Log Wood)'), ('fire-wood-chips', 'Fire Wood (Wood Chips)'), ('fire-wood-pellets', 'Fire Wood (Wood Pellets)'), ('char-coal', 'Charcoal'), ('ignite', 'Ignite'), ('none', 'None'), ('other', 'Other')], max_length=50, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='power_input',
            field=models.DecimalField(blank=True, db_column='power_input_kw', decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hot Water System Power Input (kW)'),
        ),
    ]