# Generated by Django 5.1.2 on 2026-02-13 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_hot_water_system_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwatersystem',
            name='fuel_consumption_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fuel Consumption Unit'),
        ),
        migrations.AddField(
            model_name='hotwatersystem',
            name='total_fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Fuel Consumption (Boiler)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='type_of_hot_water_system',
            field=models.CharField(choices=[('heat-pump', 'Heat Pump Water Heater'), ('boiler', 'Boiler'), ('solar', 'Water Heaters')], db_column='system_type', max_length=50, verbose_name='Type of Hot Water System'),
        ),
    ]