# Generated by Django 5.1.2 on 2026-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_add_boiler_fuel_consumption_rename_solar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotwatersystem',
            name='fuel_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('natural-gas', 'Natural Gas'), ('lpg', 'LPG'), ('diesel', 'Diesel'), ('kerosene', 'Kerosene'), ('coal', 'Coal'), ('solar', 'Solar'), ('light-fuel-oil', 'Light Fuel Oil'), ('heavy-fuel-oil', 'Heavy Fuel Oil'), ('lignite', 'Lignite'), ('fire-wood-log', 'Fire Wood (Log Wood)'), ('fire-wood-chips', 'Fire Wood (Wood Chips)'), ('fire-wood-pellets', 'Fire Wood (Wood Pellets)'), ('char-coal', 'Charcoal'), ('ignite', 'Ignite'), ('none', 'None'), ('other', 'Other')], max_length=50, verbose_name='Fuel Type'),
        ),
    ]
