# Generated by Django 5.1.2 on 2026-02-17 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_add_solar_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_smart_system',
            field=models.BooleanField(default=False, verbose_name='Building Smart System Installation'),
        ),
        migrations.AddField(
            model_name='building',
            name='renewable_energy_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Renewable Energy Installation (%)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='cooling_type',
            field=models.CharField(blank=True, choices=[('window-ac', 'Window air conditioners'), ('split-ac', 'Split air conditioners'), ('vrf-system', 'Variable refrigerant flow (VRF) systems'), ('packaged-ac', 'Packaged/Ductable air conditioners'), ('chiller-water', 'Chiller system - Water cooled chiller'), ('chiller-air', 'Chiller system - Air cooled chiller')], max_length=50, null=True, verbose_name='Coolingting Type'),
        ),
    ]
