# Generated by Django 5.1.2 on 2026-02-17 08:08

import django.db.models.deletion
import pages.models.building
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_add_renewable_energy_smart_system_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.building.certification_upload_path, verbose_name='Certification File'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_boq',
            field=models.BooleanField(default=False, verbose_name='Has Design Drawings / BoQ'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_certification',
            field=models.BooleanField(default=False, verbose_name='Has Certification'),
        ),
        migrations.CreateModel(
            name='BuildingBoQFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.building.boq_file_upload_path, verbose_name='BoQ / Design File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_files', to='pages.building')),
            ],
            options={
                'verbose_name': 'Building BoQ File',
                'verbose_name_plural': 'Building BoQ Files',
            },
        ),
    ]
