# Generated by Django 5.1.2 on 2026-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_add_building_certification_boq_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='dimension',
            field=models.CharField(choices=[('area', 'm²'), ('length', 'm'), ('mass', 'kg'), ('volume', 'm³'), ('pcs', 'pcs')], default='area', max_length=20, verbose_name='Assembly type'),
        ),
    ]