# Generated by Django 5.1.2 on 2026-02-19 15:10
# The DB already has country_id column and unique constraint from a previous state.
# 0012_alter_categorysubcategory_unique_together_and_more already added the country
# field and unique_together in Django state. This migration only syncs the EPD type
# field change and ensures the dependency ordering is correct.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0012_alter_categorysubcategory_unique_together_and_more'),
        ('pages', '0026_add_pcs_assembly_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epd',
            name='type',
            field=models.CharField(choices=[('official', 'From a verified ILCD+EPD source'), ('official_non_standard', 'Official from non ILCD + EPD format'), ('custom', 'Created by user'), ('generic', 'Representative EPD for a country')], max_length=255, verbose_name='Type'),
        ),
    ]
