# Generated by Django 5.1.2 on 2026-02-19 15:10
# The DB already has country_id column and unique constraint from a previous state.
# This migration only updates Django's migration state to match.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0026_add_pcs_assembly_dimension'),
    ]

    operations = [
        # Sync state only — DB already has country_id column and the unique constraint.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='categorysubcategory',
                    name='country',
                    field=models.ForeignKey(blank=True, help_text='Leave blank to mark this as global', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
                ),
                migrations.AlterUniqueTogether(
                    name='categorysubcategory',
                    unique_together={('category', 'subcategory', 'country')},
                ),
            ],
        ),
        migrations.AlterField(
            model_name='epd',
            name='type',
            field=models.CharField(choices=[('official', 'From a verified ILCD+EPD source'), ('official_non_standard', 'Official from non ILCD + EPD format'), ('custom', 'Created by user'), ('generic', 'Representative EPD for a country')], max_length=255, verbose_name='Type'),
        ),
    ]