# Generated by Django 5.1.2 on 2026-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_add_country_to_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolingsystemairconditioner',
            name='cooling_capacity_per_unit_kw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cooling Capacity per Unit (kW)'),
        ),
        migrations.AddField(
            model_name='coolingsystemairconditioner',
            name='eer_iseer_cop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='EER / ISEER / COP'),
        ),
        migrations.AddField(
            model_name='coolingsystemairconditioner',
            name='power_input_per_unit_kw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Power Input per Unit (kW)'),
        ),
        migrations.AlterField(
            model_name='coolingsystemairconditioner',
            name='total_cooling_load_rt',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Cooling Load for Split/VRV (RT)'),
        ),
    ]
