# Generated by Django 5.1.2 on 2026-03-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_refrigerant_quantity_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingsystemairconditioner',
            name='total_energy_consumption_kwh_per_year',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Total Energy Consumption of Cooling System Annually (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='coolingsystemchiller',
            name='total_energy_consumption_kwh_per_year',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Total Energy Consumption of Chiller System Annually (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='hotwatersystem',
            name='total_energy_consumption_kwh_per_year',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Total Energy Consumption Annually (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='liftescalatorsystem',
            name='annual_energy_consumption_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Annual Lift System Energy Consumption (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='total_energy_consumption_kwh_per_year',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Total Energy Consumption of Lighting System Annually (kWh/year)'),
        ),
        migrations.AlterField(
            model_name='ventilationsystem',
            name='total_energy_consumption_kwh_per_year',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Total Energy Consumption of Ventilation System Annually (kWh/year)'),
        ),
    ]