# Generated by Django 5.1.2 on 2026-03-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_categorysubcategory_unique_together_and_more'),
        ('pages', '0012_alter_epd_type'),
        ('pages', '0030_energy_consumption_decimal'),
    ]

    operations = [
    ]
