# Generated by Django 5.1.2 on 2026-03-14 10:41
#
# Uses SeparateDatabaseAndState for fields that already exist (or don't exist)
# in the live database so this migration is safe to apply without touching
# the production schema. The test runner builds the DB from scratch using
# migrations, so the state operations ensure the test DB is created correctly.

import django.db.models.deletion
from cities_light.models import Country
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0031_assembly_template_fields'),
    ]

    operations = [
        # number_of_stars was removed from the model but never existed in the
        # live DB (it was dropped before a migration was created). We only
        # update Django's migration state here — no DDL issued.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='hotwatersystem',
                    name='number_of_stars',
                ),
            ],
        ),

        # AlterField for draft/public on assembly — only changes help_text in
        # the ORM state; the columns already have the right type in the DB.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='assembly',
                    name='draft',
                    field=models.BooleanField(default=False, help_text='Whether this assembly is in draft state'),
                ),
                migrations.AlterField(
                    model_name='assembly',
                    name='public',
                    field=models.BooleanField(default=False, help_text='Whether this template is publicly accessible'),
                ),
            ],
        ),

        # country FK on CategorySubcategory — already exists in the live DB,
        # so database_operations is empty. The test runner will create it via
        # the state_operations below.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='categorysubcategory',
                    name='country',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Leave blank to mark this as global',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='cities_light.country',
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name='categorysubcategory',
                    unique_together={('category', 'subcategory', 'country')},
                ),
            ],
        ),
    ]