# Generated by Django 5.1.2 on 2026-03-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_merge_20260305_2157'),
        ('pages', '0036_building_climate_zone_fk'),
    ]

    operations = [
    ]
