# Generated by Django 5.1.2 on 2026-03-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0037_merge_20260314_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysubcategory',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Leave blank to mark this as global', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
    ]
