# Generated by Django 5.1.2 on 2026-05-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_categorysubcategory_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooling_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Cooling System (kWh/yr)')),
                ('is_manual_cooling', models.BooleanField(default=False)),
                ('ventilation_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Ventilation System (kWh/yr)')),
                ('is_manual_ventilation', models.BooleanField(default=False)),
                ('lighting_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Lighting System (kWh/yr)')),
                ('is_manual_lighting', models.BooleanField(default=False)),
                ('lift_escalator_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Lift & Escalator System (kWh/yr)')),
                ('is_manual_lift_escalator', models.BooleanField(default=False)),
                ('hot_water_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Hot Water System (kWh/yr)')),
                ('is_manual_hot_water', models.BooleanField(default=False)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy_summary', to='pages.building', verbose_name='Building')),
            ],
            options={
                'verbose_name': 'Energy Consumption Summary',
                'verbose_name_plural': 'Energy Consumption Summaries',
            },
        ),
    ]
