# Generated by Django 5.1.2 on 2026-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_energy_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysummary',
            name='total_override_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Total Annual Energy Consumption Override (kWh/yr)'),
        ),
    ]
