# Generated by Django 5.1.2 on 2026-05-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_energy_summary_total_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='seismic_zone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seismic Zone / Risk Level'),
        ),
    ]
