# Generated by Django 5.1.2 on 2026-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_add_design_drawings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='cooling_not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='hot_water_not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='lift_not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='lighting_not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='ventilation_not_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
