# Generated by Django 5.1.2 on 2026-06-18 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_add_system_not_applicable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='has_boq',
        ),
        migrations.RemoveField(
            model_name='building',
            name='has_design_drawings',
        ),
        migrations.AddField(
            model_name='building',
            name='boq_status',
            field=models.CharField(choices=[('not_available', 'Not available'), ('available_pending', 'Available — upload pending'), ('uploaded', 'Uploaded')], default='not_available', max_length=20, verbose_name='Bill of Quantities Status'),
        ),
        migrations.AddField(
            model_name='building',
            name='design_drawings_status',
            field=models.CharField(choices=[('not_available', 'Not available'), ('available_pending', 'Available — upload pending'), ('uploaded', 'Uploaded')], default='not_available', max_length=20, verbose_name='Design Drawings Status'),
        ),
        migrations.AlterField(
            model_name='building',
            name='renewable_energy_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Renewable Energy Installation (%)'),
        ),
    ]
