# Generated by Django 5.1.2 on 2026-07-09 19:12

from django.db import migrations, models

UNIT_FIELDS = [
    ('buildingassemblysimulated', 'unit'),
    ('epd', 'declared_unit'),
    ('operationalproduct', 'input_unit'),
    ('simulatedoperationalproduct', 'input_unit'),
    ('structuralproduct', 'input_unit'),
]

OLD_TO_NEW = {'tones': 'ton', 'tones_km': 'ton_km'}


def backfill_tones_to_ton(apps, schema_editor):
    for model_name, field_name in UNIT_FIELDS:
        model = apps.get_model('pages', model_name)
        for old_value, new_value in OLD_TO_NEW.items():
            model.objects.filter(**{field_name: old_value}).update(**{field_name: new_value})


def revert_ton_to_tones(apps, schema_editor):
    for model_name, field_name in UNIT_FIELDS:
        model = apps.get_model('pages', model_name)
        for old_value, new_value in OLD_TO_NEW.items():
            model.objects.filter(**{field_name: new_value}).update(**{field_name: old_value})


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_add_document_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingassemblysimulated',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('ton_km', 'Ton per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit of Quantity'),
        ),
        migrations.AlterField(
            model_name='epd',
            name='declared_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('ton_km', 'Ton per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Declared Unit'),
        ),
        migrations.AlterField(
            model_name='operationalproduct',
            name='input_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('ton_km', 'Ton per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit for quantity of EPD'),
        ),
        migrations.AlterField(
            model_name='simulatedoperationalproduct',
            name='input_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('ton_km', 'Ton per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit for quantity of EPD'),
        ),
        migrations.AlterField(
            model_name='structuralproduct',
            name='input_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('cm2', 'Square Centimeter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('pcs', 'Pieces'), ('kwh', 'Kilowatt Hour'), ('l', 'Liter'), ('m2r1', 'Square Meter Rate 1'), ('km', 'Kilometer'), ('ton_km', 'Ton per Kilometer'), ('kgm3', 'Kilogram per Cubic Meter'), ('unknown', 'Unknown'), ('percent', 'Percent'), ('mj', 'Megajoule'), ('kgco2e', 'kgCO2e'), ('kgcfc11e', 'kgCFC11e'), ('kgnmvoce', 'kg NMVOC eq.'), ('moleh+e', 'Mole of H+ eq.'), ('molene', 'Mole of N eq.'), ('kgpe', 'kg P eq.'), ('kgne', 'kg N eq.'), ('m3we', 'm³ world equiv.'), ('kgsbe', 'kg Sb eq.'), ('tr', 'Ton of Refrigeration'), ('kw', 'Kilowatt'), ('m^3/h', 'Cubic Meters per Hour'), ('cfm', 'Cubic Feet per Minute'), ('celsius', '°Celsius'), ('fahrenheit', '°Fahrenheit'), ('liter', 'Liter')], default='unknown', max_length=20, verbose_name='Unit for quantity of EPD'),
        ),
        migrations.RunPython(backfill_tones_to_ton, revert_ton_to_tones),
    ]
