# Generated by Django 5.1.2 on 2026-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_assemblycategory_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='dimension',
            field=models.CharField(choices=[('area', 'm²'), ('length', 'm'), ('mass', 'kg'), ('ton', 'ton'), ('volume', 'm³'), ('pcs', 'pcs')], default='area', max_length=20, verbose_name='Assembly type'),
        ),
    ]
