# Generated by Django 5.1.2 on 2026-07-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_rename_operational_carriers'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='example_variant',
            field=models.CharField(blank=True, choices=[('typical', 'Typical'), ('low_carbon', 'Low-carbon')], help_text='For example buildings only: which variant.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='is_example',
            field=models.BooleanField(db_index=True, default=False, help_text='Read-only reference/example building shown in the Examples area; users clone it to start their own building. Excluded from user dashboards.'),
        ),
    ]
