# Generated by Django 5.1.2 on 2026-07-26 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_building_example_variant_building_is_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='renewable_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='On-site renewable electricity generated per year.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Renewable Energy (kWh/yr)'),
        ),
        migrations.AddField(
            model_name='building',
            name='renewable_input_mode',
            field=models.CharField(choices=[('percent', 'Percentage'), ('kwh', 'kWh/yr')], default='percent', help_text='Whether renewable energy was entered as a percentage or in kWh/yr.', max_length=8),
        ),
        migrations.AddField(
            model_name='energysummary',
            name='is_manual_plug_load',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='energysummary',
            name='plug_load_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Plug & Equipment Loads (kWh/yr)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='renewable_energy_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Share of the building's electricity supplied by on-site renewables.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Renewable Energy Installation (%)'),
        ),
    ]
