# Generated by Django 5.1.2 on 2026-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_building_renewable_energy_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralproduct',
            name='sourcing_scenario',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('imported', 'Imported')], help_text='A4 transport sourcing scenario override (null = category default).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='structuralproduct',
            name='waste_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='A5 construction waste rate as a fraction, e.g. 0.05 (null = category default).', max_digits=5, null=True),
        ),
    ]
