# Generated by Django 5.1.2 on 2026-08-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_structuralproduct_sourcing_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralproduct',
            name='a4_distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='A4 transport distance override in km (null = scenario default).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='structuralproduct',
            name='a4_ef',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='A4 transport emission factor override, kg CO2e/tonne-km (null = country default).', max_digits=8, null=True),
        ),
    ]
