# Generated by Django 5.1.2 on 2026-10-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0053_structuralproduct_a4_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingSpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Space / room')),
                ('is_common', models.BooleanField(default=False, help_text='Shown for every building type rather than one category.')),
                ('building_categories', models.JSONField(blank=True, default=list, help_text='BuildingCategory names this space applies to. Empty when is_common.')),
                ('legacy', models.BooleanField(default=False, help_text='One of the original six room types. Kept so existing records still display, but hidden when adding a new lighting system.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Lighting space type',
                'ordering': ['-is_common', 'sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='lightingsystem',
            name='room_type',
            field=models.CharField(max_length=50, verbose_name='Room Type'),
        ),
        migrations.CreateModel(
            name='LightingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_category', models.CharField(blank=True, help_text="Used when basis is 'building'.", max_length=120, null=True)),
                ('basis', models.CharField(choices=[('room', 'Per room'), ('building', 'Whole building average')], default='room', max_length=20)),
                ('lpd_w_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Reference lighting power density (W/m²)')),
                ('lux', models.PositiveIntegerField(blank=True, null=True, verbose_name='Required illuminance (lux)')),
                ('standard', models.CharField(max_length=120)),
                ('tier', models.CharField(blank=True, help_text='Stringency tier where the standard has them (ECBC / ECBC+ / Super ECBC).', max_length=40, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_references', to='cities_light.country')),
                ('space_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pages.lightingspacetype')),
            ],
            options={
                'verbose_name': 'Lighting reference value',
                'indexes': [models.Index(fields=['country', 'basis'], name='pages_light_country_602aeb_idx')],
            },
        ),
    ]
