# Generated by Django 5.1.2 on 2026-10-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('pages', '0054_lighting_space_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epd',
            unique_together={('UUID', 'name', 'country')},
        ),
    ]
