# Generated by Django 5.1.2 on 2026-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_epd_unique_per_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='epd',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='epd',
            name='material_name',
            field=models.CharField(blank=True, help_text='What the product is, independent of brand. Drives search and sorting.', max_length=255, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='epd',
            name='product_name',
            field=models.CharField(blank=True, help_text="Manufacturer's name for this specific product, where it has one.", max_length=255, null=True, verbose_name='Product / trade name'),
        ),
        migrations.AddField(
            model_name='epd',
            name='source_name',
            field=models.CharField(blank=True, help_text='The title exactly as it appeared in the source document. Kept so a figure can always be traced back after the display name changes.', max_length=255, null=True, verbose_name='Original title'),
        ),
    ]
