# Generated by Django 5.1.2 on 2025-01-16 12:00

import encrypted_json_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_json_fields.fields.EncryptedEmailField(crypter=None, unique=True),
        ),
    ]
