# Generated by Django 5.1.2 on 2025-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customcity_customregion_alter_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_flag',
            field=models.BooleanField(default=True, verbose_name='Share with BEAT tool maintainers'),
        ),
    ]
