# Generated by Django 5.1.2 on 2026-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('data_manager', 'Data Manager'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='viewer', max_length=20),
        ),
    ]
