# Generated by Django 5.1.2 on 2025-01-14 16:41

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(default=2, verbose_name='mobile phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='last name'),
        ),
    ]
